### ISSUE TITLE
請問列印發票則必須有統編？ 那沒有統編 又要列印發票的User要如何處理？

### ISSUE THREAD

**Issue by enkuo0828** [ECPay/Invoice_Python#1]
https://github.com/ECPay/Invoice_Python/blob/3c52681d23aa7a788d13d6ba3dd8411c96754ee7/ecpay_invoice/ecpay_main.py#L378-L381

並且我在其他電子發票sdk沒有看到相同的檢查
https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L222
https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L326

**Comment by AllennChang** [comment]
HI 您好, 新版已移除相關檢核規則, 若有任何問題, 歡迎再跟我們反應 感謝您
