### ISSUE TITLE
Parameter error in ecpay_main

### ISSUE THREAD

**Issue by brianchul** [ECPay/Invoice_Python#3]
In ecpay_main line 31 and 32 shows:

`self.Send['CarruerType'] = ''`
`self.Send['CarruerNum'] = ''`

but in latest document says is 

<img width="1172" alt="截圖 2020-06-09 下午3 56 56" src="https://user-images.githubusercontent.com/18157275/84121535-e21c1280-aa69-11ea-9689-9d510b017941.png">

**Comment by AllennChang** [comment]
您好, 感謝您的題問,  目前新版規格參數名稱跟舊版不同, sdk串接是舊版規格, 請參考
https://github.com/ECPay/Invoice_Python/blob/master/B2C%E9%9B%BB%E5%AD%90%E7%99%BC%E7%A5%A8%E4%BB%8B%E6%8E%A5%E6%8A%80%E8%A1%93%E6%96%87%E4%BB%B6.pdf

**Comment by brianchul** [comment]
好的，會參考新版規格
